### PR TITLE
Adds Tag support to plugin.

### PR DESCRIPTION
**Pull request by pgraham3**
Adds `X-PM-Tag` as a 'recognized header' so users can set a Tag when sending with the plugin.

### CODE REVIEW

**Comment by DorZuberi** [comment]
Anything new about this PR?
Adding a Tag is very basic and required option...

**Comment by pgraham3** [comment]
@DorZuberi I'll try to find some time to resurrect this PR this week.

**Comment by DorZuberi** [comment]
@pgraham3 great, I would add a filter to the headers as well.

**Comment by pgraham3** [comment]
Moving changes to a fresh PR for better diff. https://github.com/ActiveCampaign/postmark-wordpress/pull/103

**Pull request closed without merging**
